services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      RAM_SIZE: "6G"
      CPU_CORES: "4"
      USERNAME: "Docker"
      PASSWORD: ""
      REGION: "en-US"
      KEYBOARD: "en-US"
#      VERSION: "win11"
#      VERSION: "https://s3.eu-central-1.wasabisys.com/juno-deps/tiny11-2311-x64.iso"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 4003:3389/tcp
      - 4003:3389/udp
    stop_grace_period: 2m
    volumes:
      - /mnt/data/temp/tiny11-2311-x64.iso:/custom.iso
      - /mnt/data/temp/docker-rnd/windows/scripts:/oem
      - /mnt/data/temp/docker-rnd/windows/storage:/storage
      - /mnt/data/temp/docker-rnd/windows/data:/data
